Description: >

    This CloudFormation template will deploy a full CI/CD pipeline for Go
    development. It includes building with AWS CodeBuild, and infrastructure
    deployment via AWS CloudFormation. It will create an AWS CodePipeline for
    orchastrating builds, testing and deployments to beta and production 
    environments. 

Parameters:
    
    ApplicationName: 
        Description: This will be used to name the pipeline and build resources
        Type: String
        AllowedPattern: '[A-Za-z0-9-]+'
    
    ArtifactS3Bucket:
        Description: An existing S3 bucket within this AWS account
        Type: String

    GitHubOAuthToken: 
        Description: Create a token with 'repo' and 'admin:repo_hook' permissions here https://github.com/settings/tokens
        Type: String
        NoEcho: true

    GitHubUser:
        Description: Enter GitHub username of the repository owner
        Type: String

    GitHubRepository:
        Description: Enter the repository name that should be monitored for changes
        Type: String

    GitHubBranch:
        Description: Enter the GitHub branch to monitored
        Type: String
        Default: master

    CodePipelineRole:
        Description: ARN of the CodePipeline Role.
        Type: String
        Default: arn:aws:iam::281782457076:role/DevOps-Training-CodePipelineServiceROle
    
    CodeBuildRole:
        Description: ARN of the CodeBuild Role
        Type: String
        Default: arn:aws:iam::281782457076:role/DevOps-Training-CodeBuildServiceRole
    
    CodePipelineCloudFormationRole:
        Description: ARN of the CodePipeline CloudFormation Role
        Type: String
        Default: arn:aws:iam::281782457076:role/DevOps-Training-CloudFormationServiceRole

    CodeDeployServiceRole:
        Description: ARN of the CodeDeploy Role
        Type: String
        Default: arn:aws:iam::281782457076:role/DevOps-Training-CodeDeployServiceRole

Metadata:

    AWS::CloudFormation::Interface:
        ParameterGroups:
            - 
                Label: 
                    default: Application Configuration
                Parameters:
                    - ApplicationName
                    - ArtifactS3Bucket
            - 
                Label:
                    default: GitHub Configuration
                Parameters:
                    - GitHubOAuthToken
                    - GitHubUser
                    - GitHubRepository
                    - GitHubBranch
            
        ParameterLabels:
            ApplicationName: 
                default: Application Name
            ArtifactS3Bucket: 
                default: CodePipeline S3 Bucket
            GitHubRepository: 
                default: Repository Name
            GitHubUser: 
                default: Repository Owner
            GitHubBranch: 
                default: Repository Branch
            GitHubOAuthToken: 
                default: OAuth2 Token

Resources:

    CodePipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            Name: !Ref ApplicationName
            RoleArn: !Ref CodePipelineRole
            ArtifactStore: 
                Type: S3
                Location: !Ref ArtifactS3Bucket
            Stages:
                - 
                    Name: Source
                    Actions:
                        -
                            Name: GitHub
                            ActionTypeId:
                                Category: Source
                                Owner: ThirdParty
                                Version: 1
                                Provider: GitHub
                            OutputArtifacts:
                                -  Name: Source
                            Configuration:
                                Owner: !Ref GitHubUser
                                Repo: !Ref GitHubRepository
                                Branch: !Ref GitHubBranch
                                OAuthToken: !Ref GitHubOAuthToken
                -
                    Name: Build
                    Actions:
                        -
                            Name: CodeBuild
                            InputArtifacts:
                                - Name: Source
                            ActionTypeId: 
                                Category: Build
                                Owner: AWS
                                Version: 1
                                Provider: CodeBuild
                            OutputArtifacts:
                                - Name: Built
                            Configuration: 
                                ProjectName: !Ref CodeBuild
                -
                    Name: Staging
                    Actions:
                        - 
                            Name: DeployInfrastructure
                            RunOrder: 1
                            InputArtifacts:
                                - Name: Built
                            ActionTypeId:
                                Category: Deploy
                                Owner: AWS
                                Version: 1
                                Provider: CloudFormation
                            Configuration:
                                ActionMode: REPLACE_ON_FAILURE
                                RoleArn: !Ref CodePipelineCloudFormationRole
                                Capabilities: CAPABILITY_NAMED_IAM
                                StackName: !Sub ${ApplicationName}-staging
                                TemplatePath: Built::cloudformation/infrastructure.yml
                                TemplateConfiguration: Built::config/staging.conf
                                ParameterOverrides: !Sub |
                                    {
                                        "ApplicationName": "${ApplicationName}",
                                        "EnvironmentName": "staging",
                                        "ArtifactS3Bucket": "${ArtifactS3Bucket}"
                                    }
                        - 
                            Name: DeployApplication
                            RunOrder: 2
                            InputArtifacts: 
                                - Name: Built
                            ActionTypeId:
                                Category: Deploy
                                Owner: AWS
                                Version: 1
                                Provider: CodeDeploy
                            Configuration: 
                                ApplicationName: !Ref ApplicationName
                                DeploymentGroupName: staging
                - 
                    Name: Approvals
                    Actions:
                        - 
                            Name: ProductionGate
                            ActionTypeId: 
                                Category: Approval
                                Owner: AWS
                                Version: 1
                                Provider: Manual
                                
                -
                    Name: Production
                    Actions:
                        - 
                            Name: DeployInfrastructure
                            RunOrder: 1
                            InputArtifacts:
                                - Name: Built
                            ActionTypeId:
                                Category: Deploy
                                Owner: AWS
                                Version: 1
                                Provider: CloudFormation
                            Configuration:
                                ActionMode: CREATE_UPDATE
                                RoleArn: !Ref CodePipelineCloudFormationRole
                                Capabilities: CAPABILITY_NAMED_IAM
                                StackName: !Sub ${ApplicationName}-production
                                TemplatePath: Built::cloudformation/infrastructure.yml
                                TemplateConfiguration: Built::config/production.conf
                                ParameterOverrides: !Sub |
                                    {
                                        "ApplicationName": "${ApplicationName}",
                                        "EnvironmentName": "production",
                                        "ArtifactS3Bucket": "${ArtifactS3Bucket}"
                                    }
                        - 
                            Name: DeployApplication
                            RunOrder: 2
                            InputArtifacts: 
                                - Name: Built
                            ActionTypeId:
                                Category: Deploy
                                Owner: AWS
                                Version: 1
                                Provider: CodeDeploy
                            Configuration: 
                                ApplicationName: !Ref ApplicationName
                                DeploymentGroupName: production
                        

    CodeBuild:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: !Ref ApplicationName
            Description: !Sub Build project for ${ApplicationName}
            ServiceRole: !Ref CodeBuildRole
            Source:
                Type: CODEPIPELINE
            Environment:
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/golang:1.7.3
                Type: LINUX_CONTAINER
                EnvironmentVariables:
                    - 
                        Name: ARTIFACT_S3_BUCKET
                        Value: !Sub ${ArtifactS3Bucket}
            Artifacts:
                Name: !Ref ApplicationName
                Type: CODEPIPELINE

    CodeDeployApplication:
        Type: AWS::CodeDeploy::Application
        Properties:
            ApplicationName: !Sub ${ApplicationName}


Outputs:

    CodePipelineURL:
        Description: The URL for the created pipeline
        Value: !Sub https://${AWS::Region}.console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${ApplicationName}      

    CodeDeployApplication:
        Description: The CodeDeploy application used across all environments
        Value: !Ref CodeDeployApplication
        Export:
            Name: !Sub CodeDeployApplication-${ApplicationName}

    CodeDeployServiceRoleArn:
        Description: The CodeDeploy service role used across all environments
        Value: !Ref CodeDeployServiceRole
        Export:
            Name: CodeDeployServiceRole-${ApplicationName}

